package pojos;
// Generated 26/09/2024 12:13:04 AM by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProductos56;
     private Boolean estado56;
     private String nombre56;
     private Integer cantidad56;
     private String ubicacion56;

    public Productos() {
    }

    public Productos(Boolean estado56, String nombre56, Integer cantidad56, String ubicacion56) {
       this.estado56 = estado56;
       this.nombre56 = nombre56;
       this.cantidad56 = cantidad56;
       this.ubicacion56 = ubicacion56;
    }
   
    public Integer getIdProductos56() {
        return this.idProductos56;
    }
    
    public void setIdProductos56(Integer idProductos56) {
        this.idProductos56 = idProductos56;
    }
    public Boolean getEstado56() {
        return this.estado56;
    }
    
    public void setEstado56(Boolean estado56) {
        this.estado56 = estado56;
    }
    public String getNombre56() {
        return this.nombre56;
    }
    
    public void setNombre56(String nombre56) {
        this.nombre56 = nombre56;
    }
    public Integer getCantidad56() {
        return this.cantidad56;
    }
    
    public void setCantidad56(Integer cantidad56) {
        this.cantidad56 = cantidad56;
    }
    public String getUbicacion56() {
        return this.ubicacion56;
    }
    
    public void setUbicacion56(String ubicacion56) {
        this.ubicacion56 = ubicacion56;
    }




}


